services:
  bookon-frontend:
    container_name: bookon-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - bookon-network

networks:
  bookon-network:
    driver: bridge

# ishga tushirish:
# docker compose up -d --build
# docker compose logs -f --tail=100
# docker compose down
